### PR TITLE
StatisticsItem constructor, getAction, getUri methods.

### PR DESCRIPTION
**Pull request by guncha25**
Defines methods and properties to StatisticsItemInterface and implements them in StatisticsItem;
Added methods : getUri, getAction.
Modified constructor to throw InvalidArgumentException if passed uri or action is empty;

Testing suggestions:
Check if InvalidArgumentException is thrown.
Get action and uri name through getters.

Trello card -https://trello.com/c/baJUJ2hA/10-definie-initial-statistics-item-for-dispatch-event

### CODE REVIEW

**Comment by maijs** [comment]
> Use an indent of 2 spaces, with no tabs. [Drupal coding standards](https://www.drupal.org/coding-standards#indenting)

The changes in this PR feature 4 space indentation.

**Comment by james-nesbitt** [comment]
I don't like this:

---
1. the constructor receives an array that requires two elements, with no documentation about requiring those elements.  It would be much more clear to require the two values.
   
   function construct($action, $uri) {}
2. In most Drupal classes, when implementing Accessors to retrieve values, you apply Accessors to change them as well.  If you add ->getAction(), then you expect ->setAction($action) to be available.  You have not added such methods.

---

Please defend both decisions, or alternatively explain that this is inital code, with a plan for changing it in the future.

**Comment by guncha25** [comment]
1. If constructor would accept only those two variables we would complicate things in future if we would need more variables, it is easier to add some data to array than change methods.
2. On object creation data is set in appropriate variables. Since there is no reason to manipulate them there is no reason to make setters. There is no reason to set them later because we want to 'fail fast' and main purpose of StatisticsItem is to carry statistics information to dispatcher. There is no reason to modify statistic data.

**Comment by james-nesbitt** [comment]
Point #2 is conceded. Point #1 is not.

What you are doing is called "lazy parametrization."  This kind of approach hides the nature of arguments, defending the approach as "thinking of the future" (forward-thinking)  But it is considered bad-practice to have such abstract arguments.
Surely some of those arguments will always be required, and will always make sense, so they can be explicit.  You can then also include further abstract data as an array.

```
function __construct($action, $uri, $data=null) {}
```

It is always a warning when a function received only an array.  It brings us back to the days of D7 where we had massive nested arrays for configurations, that nobody could remember.

**Pull request merged**
